# Generated by Django 4.2 on 2024-07-29 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_order_store_delete_data_order_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
